version: '3.4'

services:

  zoo-paris:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-paris
    cap_add:
      - ALL
    container_name: zoo-paris
    networks:
      locknet:
        ipv4_address: 172.20.0.5
    ports:
      - 2181:2181

  locker-paris:
    depends_on:
      - zoo-paris
    links:
      - zoo-paris

  locker-tokyo:
    depends_on:
      - zoo-paris
    links:
      - zoo-paris

  locker-singapore:
    depends_on:
      - zoo-paris
    links:
      - zoo-paris

  locker-capetown:
    depends_on:
      - zoo-paris
    links:
      - zoo-paris

  locker-newyork:
    depends_on:
      - zoo-paris
    links:
      - zoo-paris
