version: '3.4'

services:

  zoo-paris:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-paris
    cap_add:
      - ALL
    container_name: zoo-paris
    networks:
      locknet:
        ipv4_address: 172.20.0.5
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.20.0.5:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-tokyo:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-tokyo
    cap_add:
      - ALL
    container_name: zoo-tokyo
    networks:
      locknet:
        ipv4_address: 172.20.0.6
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=172.20.0.6:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-singapore:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-singapore
    cap_add:
      - ALL
    container_name: zoo-singapore
    networks:
      locknet:
        ipv4_address: 172.20.0.7
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=172.20.0.7:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-capetown:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-capetown
    cap_add:
      - ALL
    container_name: zoo-capetown
    networks:
      locknet:
        ipv4_address: 172.20.0.8
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=172.20.0.8:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-newyork:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-newyork
    cap_add:
      - ALL
    container_name: zoo-newyork
    networks:
      locknet:
        ipv4_address: 172.20.0.9
    ports:
      - 2185:2181
    environment:
      ZOO_MY_ID: 5
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=172.20.0.9:2892:3892;2181

  locker-paris:
    depends_on:
      - zoo-paris
    links:
      - zoo-paris

  locker-tokyo:
    depends_on:
      - zoo-tokyo
    links:
      - zoo-tokyo

  locker-singapore:
    depends_on:
      - zoo-singapore
    links:
      - zoo-singapore

  locker-capetown:
    depends_on:
      - zoo-capetown
    links:
      - zoo-capetown

  locker-newyork:
    depends_on:
      - zoo-newyork
    links:
      - zoo-newyork
