version: '3.4'

services:

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181

  locker-paris:
    build:
      context: ./locker
      dockerfile: Dockerfile
    volumes:
      - "./locker:/usr/src/app"
    environment:
      - WHOAMI=locker-paris
      - APP=${APP}
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 4001:4001
    command: python locker.py 

  locker-tokyo:
    build:
      context: ./locker
      dockerfile: Dockerfile
    volumes:
      - "./locker:/usr/src/app"
      - "./data/tokyo:/usr/data"
    environment:
      - WHOAMI=locker-tokyo
      - APP=${APP}
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 4002:4002
    command: python locker.py 

  locker-singapore:
    build:
      context: ./locker
      dockerfile: Dockerfile
    volumes:
      - "./locker:/usr/src/app"
      - "./data/singapore:/usr/data"
    environment:
      - WHOAMI=locker-singapore
      - APP=${APP}
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 4003:4003
    command: python locker.py 

  locker-capetown:
    build:
      context: ./locker
      dockerfile: Dockerfile
    volumes:
      - "./locker:/usr/src/app"
      - "./data/capetown:/usr/data"
    environment:
      - WHOAMI=locker-capetown
      - APP=${APP}
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 4004:4004
    command: python locker.py 

  locker-newyork:
    build:
      context: ./locker
      dockerfile: Dockerfile
    volumes:
      - "./locker:/usr/src/app"
      - "./data/newyork:/usr/data"
    environment:
      - WHOAMI=locker-newyork
      - APP=${APP}
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 4005:4005
    command: python locker.py 

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/paris:/usr/data"
    environment:
      - WHOAMI=paris
      - APP=${APP}
    depends_on:
      - locker-paris
    links:
      - locker-paris
    ports:
      - 6001:6000
    command: flask run --host=0.0.0.0 --port=6000

  tokyo:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/tokyo:/usr/data"
    environment:
      - WHOAMI=tokyo
      - APP=${APP}
    depends_on:
      - locker-tokyo
    links:
      - locker-tokyo
    ports:
      - 6002:6000
    command: flask run --host=0.0.0.0 --port=6000

  singapore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/singapore:/usr/data"
    environment:
      - WHOAMI=singapore
      - APP=${APP}
    depends_on:
      - locker-singapore
    links:
      - locker-singapore
    ports:
      - 6003:6000
    command: flask run --host=0.0.0.0 --port=6000

  capetown:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/capetown:/usr/data"
    environment:
      - WHOAMI=capetown
      - APP=${APP}
    depends_on:
      - locker-capetown
    links:
      - locker-capetown
    ports:
      - 6004:6000
    command: flask run --host=0.0.0.0 --port=6000

  newyork:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./data/newyork:/usr/data"
    environment:
      - WHOAMI=newyork
      - APP=${APP}
    depends_on:
      - locker-newyork
    links:
      - locker-newyork
    ports:
      - 6005:6000
    command: flask run --host=0.0.0.0 --port=6000
