version: '3.4'

networks:
  locknet:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  zoo-paris:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-paris
    cap_add:
      - ALL
    container_name: zoo-paris
    networks:
      locknet:
        ipv4_address: 172.20.0.5
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.20.0.5:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-tokyo:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-tokyo
    cap_add:
      - ALL
    container_name: zoo-tokyo
    networks:
      locknet:
        ipv4_address: 172.20.0.6
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=172.20.0.6:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-singapore:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-singapore
    cap_add:
      - ALL
    container_name: zoo-singapore
    networks:
      locknet:
        ipv4_address: 172.20.0.7
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=172.20.0.7:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-capetown:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-capetown
    cap_add:
      - ALL
    container_name: zoo-capetown
    networks:
      locknet:
        ipv4_address: 172.20.0.8
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=172.20.0.8:2891:3891;2181 server.5=zoo-newyork:2892:3892;2181

  zoo-newyork:
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    restart: always
    hostname: zoo-newyork
    cap_add:
      - ALL
    container_name: zoo-newyork
    networks:
      locknet:
        ipv4_address: 172.20.0.9
    ports:
      - 2185:2181
    environment:
      ZOO_MY_ID: 5
      ZOO_SERVERS: server.1=zoo-paris:2888:3888;2181 server.2=zoo-tokyo:2889:3889;2181 server.3=zoo-singapore:2890:3890;2181 server.4=zoo-capetown:2891:3891;2181 server.5=172.20.0.9:2892:3892;2181

  paris:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./config:/usr/config"
    environment:
      - WHOAMI=paris
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - LOCKTYPE=${LOCKTYPE}
    depends_on:
      - zoo-paris
    links:
      - zoo-paris
    container_name: paris
    networks:
      locknet:
        ipv4_address: 172.20.0.25
    ports:
      - 6001:6000
    command: flask run --host=0.0.0.0 --port=6000

  tokyo:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./config:/usr/config"
    environment:
      - WHOAMI=tokyo
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - LOCKTYPE=${LOCKTYPE}
    depends_on:
      - zoo-tokyo
    links:
      - zoo-tokyo
    container_name: tokyo
    networks:
      locknet:
        ipv4_address: 172.20.0.26
    ports:
      - 6002:6000
    command: flask run --host=0.0.0.0 --port=6000

  singapore:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./config:/usr/config"
    environment:
      - WHOAMI=singapore
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - LOCKTYPE=${LOCKTYPE}
    depends_on:
      - zoo-singapore
    links:
      - zoo-singapore
    container_name: singapore
    networks:
      locknet:
        ipv4_address: 172.20.0.27
    ports:
      - 6003:6000
    command: flask run --host=0.0.0.0 --port=6000

  capetown:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./config:/usr/config"
    environment:
      - WHOAMI=capetown
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - LOCKTYPE=${LOCKTYPE}
    depends_on:
      - zoo-capetown
    links:
      - zoo-capetown
    container_name: capetown
    networks:
      locknet:
        ipv4_address: 172.20.0.28
    ports:
      - 6004:6000
    command: flask run --host=0.0.0.0 --port=6000

  newyork:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - "./application:/usr/src/app"
      - "./config:/usr/config"
    environment:
      - WHOAMI=newyork
      - APP=${APP}
      - GRANULARITY=${GRANULARITY}
      - LOCKTYPE=${LOCKTYPE}
    depends_on:
      - zoo-newyork
    links:
      - zoo-newyork
    container_name: newyork
    networks:
      locknet:
        ipv4_address: 172.20.0.29
    ports:
      - 6005:6000
    command: flask run --host=0.0.0.0 --port=6000
